from tkinter import*
window=Tk()
window.geometry("400x300")
window.title("Getting started with widgets")
lb1=Label(text="Enter 2 numbers to find a product:")
firstnum_lb1=Label(text="First number:")
firstnum_entry=Entry()
secondnum_lb1=Label(text="Second number:")
secondnum_entry=Entry()
def display():
    firstnum=firstnum_entry.get()
    secondnum=secondnum_entry.get()
    global Message
    Message=int(firstnum)*int(secondnum)
    text_box.insert(END, Message)
text_box=Text(height=3)
btn=Button(text="click me", command=display, height=3)
lb1.pack()
firstnum_lb1.pack()
secondnum_lb1.pack()
firstnum_entry.pack()
secondnum_entry.pack()
text_box.pack()
btn.pack()
window.mainloop()